spring:
  application:
    name: admin-server

server:
  port: 8769

eureka:
#  instance:
#    health-check-url: /actuator/health
  client:
#    registryFetchIntervalSeconds: 5   # 注册表获取间隔秒
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/  #注册到 EurekaServer

management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: ALWAYS  #health endpoint是否必须显示全部细节

---

# admin登录的用户名和密码
spring:
  security:
    user:
      name: admin
      password: admin

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      user:
        name: ${spring.security.user.name}         #These two are needed so that the server
        password: ${spring.security.user.password} #can access the protected client endpoints